name: Ansible Lint

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run ansible-lint
      uses: ansible/ansible-lint@main
      with:
        path: "."
        rules: "*.yml"
