---
- name: Install HAProxy
  package:
    name: haproxy
    state: present

- name: Configure HAProxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: '0644'
  notify: Restart haproxy

- name: Start and enable HAProxy
  systemd:
    name: haproxy
    state: started
    enabled: true
