---
- name: restart docker
  systemd:
    name: docker
    state: restarted

- name: restart kubelet
  systemd:
    name: kubelet
    state: restarted

- name: reload systemd
  systemd:
    daemon_reload: yes
