---
- name: Update package cache
  apt:
    update_cache: true
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"

- name: Install required system packages
  package:
    name:
      - curl
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - gnupg2
      - ntp
      - ntpdate
    state: present

- name: Configure timezone
  community.general.timezone:
    name: "{{ timezone }}"

- name: Ensure NTP is running
  systemd:
    name: ntp
    state: started
    enabled: true

- name: Disable swap
  command: swapoff -a
  ignore_errors: true
  changed_when: false

- name: Comment swap in /etc/fstab
  lineinfile:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    line: '# \1'
    backrefs: true

- name: Load kernel modules
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - br_netfilter
    - overlay

- name: Configure sysctl parameters
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    reload: true
  with_dict:
    net.bridge.bridge-nf-call-ip6tables: 1
    net.bridge.bridge-nf-call-iptables: 1
    net.ipv4.ip_forward: 1

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Install Docker
  package:
    name: docker-ce
    state: present

- name: Start and enable Docker service
  systemd:
    name: docker
    state: started
    enabled: true

- name: Add Kubernetes GPG key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add Kubernetes repository
  apt_repository:
    repo: "deb https://apt.kubernetes.io/ kubernetes-xenial main"
    state: present
